# services.yaml

parameters:
  resources: "%env(PROJECT_DIR)%/resources"

imports:
  - { resource: "_proto.yaml" }
  - { resource: "packages/dto-transformer.yaml" }
  - { resource: "packages/provider.yaml" }

services:
  Vigihdev\Faker\Contracts\ServiceProviderInterface:
    public: true
    class: 'Vigihdev\Faker\ServiceProvider'
    arguments:
      $providers: !tagged_iterator "faker.provider"

  Vigihdev\Faker\Contracts\DtoTransformerManagerInterface:
    public: true
    class: 'Vigihdev\Faker\DtoTransformerManager'
    arguments:
      $dtos: !tagged_iterator "dto_transformer"
